import dayjs from 'dayjs'

/**
 * ReportCard — A self-contained, branded card for image export.
 * Uses inline styles exclusively so html2canvas captures everything.
 */
export default function ReportCard({ stats, dateRange, hasEfficiency }) {
    const rangeLabel = dateRange
        ? `${dateRange[0].format('D MMM')} – ${dateRange[1].format('D MMM YYYY')}`
        : 'All Time'

    const bg = '#0f0f1a'
    const cardBg = '#1a1a2e'
    const borderCol = 'rgba(255,255,255,0.08)'
    const textPrimary = '#f0f0f0'
    const textSecondary = '#8b8b9e'
    const green = '#52c41a'
    const blue = '#1890ff'
    const accent = '#00b96b'

    const statBox = (label, value, color, unit = '') => (
        <div
            style={{
                background: cardBg,
                border: `1px solid ${borderCol}`,
                borderLeft: color ? `3px solid ${color}` : `1px solid ${borderCol}`,
                borderRadius: 14,
                padding: '16px 18px',
                flex: 1,
                minWidth: 0,
            }}
        >
            <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1, color: textSecondary, marginBottom: 6 }}>
                {label}
            </div>
            <div style={{ fontSize: 24, fontWeight: 700, color: color || textPrimary, lineHeight: 1.1 }}>
                {value}
                {unit && <span style={{ fontSize: 14, fontWeight: 500, marginLeft: 4, color: textSecondary }}>{unit}</span>}
            </div>
        </div>
    )

    return (
        <div
            id="evtrax-report"
            style={{
                width: 540,
                padding: 32,
                background: `linear-gradient(160deg, ${bg} 0%, #0d0d22 50%, #111126 100%)`,
                fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
                color: textPrimary,
                borderRadius: 24,
                position: 'relative',
                overflow: 'hidden',
            }}
        >
            {/* Decorative glow */}
            <div
                style={{
                    position: 'absolute',
                    top: -60,
                    right: -60,
                    width: 200,
                    height: 200,
                    background: `radial-gradient(circle, ${accent}22 0%, transparent 70%)`,
                    borderRadius: '50%',
                    pointerEvents: 'none',
                }}
            />

            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                <span style={{ fontSize: 24 }}>⚡</span>
                <span style={{ fontSize: 22, fontWeight: 700, letterSpacing: -0.3 }}>EVTrax Report</span>
            </div>
            <div style={{ fontSize: 13, color: textSecondary, marginBottom: 24, paddingLeft: 2 }}>
                {rangeLabel}
            </div>

            {/* Summary 2×2 */}
            <div style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
                {statBox('Total Cost', `฿${stats.totalCost.toFixed(2)}`, green)}
                {statBox('Energy', stats.totalEnergy.toFixed(1), blue, 'kWh')}
            </div>
            <div style={{ display: 'flex', gap: 12, marginBottom: hasEfficiency ? 20 : 0 }}>
                {statBox('Sessions', stats.totalSessions, null)}
                {statBox('Avg ฿/kWh', `฿${stats.avgCostPerKwh.toFixed(2)}`, null)}
            </div>

            {/* Efficiency row */}
            {hasEfficiency && (
                <>
                    <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1, color: textSecondary, marginBottom: 8 }}>
                        Efficiency
                    </div>
                    <div style={{ display: 'flex', gap: 10 }}>
                        {statBox('Distance', `${stats.totalDistance.toFixed(0)}`, null, 'km')}
                        {statBox('kWh/100km', stats.efficiency.toFixed(1), blue)}
                        {stats.costPerKm != null && statBox('฿/km', `฿${stats.costPerKm.toFixed(2)}`, green)}
                    </div>
                </>
            )}

            {/* Footer */}
            <div
                style={{
                    marginTop: 24,
                    paddingTop: 16,
                    borderTop: `1px solid ${borderCol}`,
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                }}
            >
                <span style={{ fontSize: 11, color: textSecondary }}>
                    Generated by EVTrax
                </span>
                <span style={{ fontSize: 11, color: textSecondary }}>
                    {dayjs().format('D MMM YYYY · HH:mm')}
                </span>
            </div>
        </div>
    )
}
